dev_deployment_artifacts: true

networks:
    networks:
        development:
            explorer: "https://api.bscscan.com/api"
            host: "https://compatible-summer-fog.bsc.quiknode.pro/32facf57be73f6c1ac993db82fb25a7737eea3d0"
        # bsc-main:
        #     host: "https://compatible-summer-fog.bsc.quiknode.pro/32facf57be73f6c1ac993db82fb25a7737eea3d0"
        default: development

reports:
    exclude_contracts:
        - ERC20
        - SafeERC20
        - Address
        - TransparentUpgradeableProxy
        - ERC1967Upgrade
        - Ownable
        - OwnableUpgradeable
        - MintableERC20
        - PoolHelperFactoryLib
        - ProxyAdmin
        - ERC20FactoryLib
        - VTX
        - xPTP
        - PoolHelper
        - ComputeAPR
        - MainStakingV2

compiler:
    solc:
        version: 0.8.7
        optimizer:
            enabled: true
            runs: 999
        remappings:
            - "@openzeppelinUpgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.4.2"
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"
dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.4.2
    - OpenZeppelin/openzeppelin-contracts-upgradeable@4.4.2
dotenv: .env
